web:
  build: .
  ports:
    - 80:80
  volumes:
    - ./log:/var/log
  links:
    - postgres
    - redis
  # env vars are replaced in /craft/config
  environment:
    # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
    LANG: C.UTF-8

    # REDIS is linked
    REDIS_HOST: redis

    # DB is linked
    DB_HOST: postgres
    DB_NAME: craft3beta
    DB_PORT: 5432
    DB_USER: craft3beta
    DB_PASS: secret

postgres:
  image: postgres:latest
  environment:
    POSTGRES_USER: craft3beta
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: craft3beta
    POSTGRES_INITDB_ARGS: "-E UTF8"
  volumes:
    # Persistent data
    - /var/lib/postgresql/data

redis:
  image: redis:alpine
  volumes:
    - /data:/data
